### ISSUE TITLE
Project Outline, scope

### ISSUE THREAD

**Issue by r-spell** [hiroko-lc101/liftoff-assignments#1]
Love the overview and the story behind the project!

I think you have a lot of great ideas for features, but some of them can be broken into quite a few stories.  In your overview you say "The only feature that was online was displaying Fitness Test questions. All the rest was done via paper-based materials. I decided to make this project as an attempt to move Mathercise online to run it smoother, more efficient and more accurate with fewer resources." What is the _minimum viable product_ which will help you to get away from the paper? Or just replace one of the steps where paper is needed?  

Maybe you can start with one of the most important of these three: 
- Student management: Admin will be able to setup students profiles.
- Flash card management: Admin will be able to create, edit and delete flash cards.
OR
- Fitness Test management: Admin will be able to create and edit Fitness Test for each level.

Each of these would be great for a project because it would incorporate CRUD (create, read, update, delete). It would be cool if you could do 1-2 of them, but it might be a lot to do all three of them in an 8-week period.

**Comment by hiroko-lc101** [comment]
Fitness Test feature is most important to me, but if I need to choose one or two features from the three given, I'd choose flash card management and Fitness Test management over student management.

**Comment by r-spell** [comment]
I think I was misunderstanding.

The main thing was I wanted you to do less of the whole project idea, at least initially.  

If you just do the Fitness Test Feature, can you help me know a little better what that means? 

What are some of the Features of a Fitness Test?  You said "The only feature that was online was displaying Fitness Test questions." Do you mean the student even answers the questions on paper?

If you do the Fitness Test Feature can you help me understand a bit more what that means? I think that is probably good just want to check it has some CRUD aspects to it (objects users can Create, Read, Update, Delete, via the app) and that it's not to big to finish. But I think it could be a great starting point from what I do understand. 

I love the general idea and reason for the project. 😄

**Comment by hiroko-lc101** [comment]
The Fitness Test/assessment is currently run by volunteers. A volunteer works with a student at a time. Each student has a Fitness Test of their level installed on their iPad (supposedly... often times it's missing from their iPad and it takes extra time to setup and start an assessment). I can't remember exactly what format Fitness Tests are, but I think it's something like a keynote file. It basically has a question, for example, 12+1,  on a slide and it displays slides one after another automatically. The student verbally answers the question, and a volunteer does the math in his/her head (as the correct answers are not available anywhere!) and logs on paper if the student answered it correctly or not. After a few seconds, the next question is displayed. Once the student goes through all questions, the volunteer counts how many questions are answered correctly, and calculate the score (% of correct answers) and judge if the student passed the level. 
I would like to have a program which can be accessed from any iPad without any installation, and calculates score automatically. 
As a Fitness Test is a series of math questions, it has CRUD aspect. Math questions/flash cards also have CRUD aspect.

**Comment by r-spell** [comment]
Ok sounds good and from Mockups I understand a bit more.
