### ISSUE TITLE
Project Outline - Not sure if I understand what italics specifies

### ISSUE THREAD

**Issue by r-spell** [hiroko-lc101/liftoff-assignments#2]
You use italics in the description for these two sections in the features:

 "Fitness Test: Admin will be able to assess students. Web-based Fitness Test eliminates the need of installing Fitness Test onto every student's iPad. It checks students' answers and calculates scores correctly and automatically. It requires less time to test a student, hence more students could take a test within the time allocated for Fitness Test."
"Progress monitoring: Admin will be able to check students' progress, create reports, run various analysis. Web app collects correct data automatically, such as test date, correct answers, incorrect answers, scores, current level, how often students did Daily Exercise and how often they had Fitness Test. It can flag students who are tested less often than others or flag students who are doing Daily Exercise less often."

These both seem like really big stories! Are these things that you are thinking you *might* do in future? They seem like they could be difficult to accomplish in the 8-week course.

**Comment by hiroko-lc101** [comment]
I used italics to explain what would be improved/different with this Mathercise app compared to the way Mathercise program is currently run. These are the main reasons why I thought creating Mathercise app would help run the program. Fitness Test feature is most important to me, I would like to focus on Flash card management, Fitness Test management, and Fitness Test more than focusing on Student management.

**Comment by hiroko-lc101** [comment]
Closing the issue
