### ISSUE TITLE
Project Outline - Not sure what parentheses signify

### ISSUE THREAD

**Issue by r-spell** [hiroko-lc101/liftoff-assignments#3]
In the discussion of the features for students, you use parentheses.  Is this because you are thinking they might be future steps but not for this 8-week project? If so that sounds like a good approach 👍 It's a really cool project idea and a lot for 8 weeks, I think doing the admin side first might be a good approach  :smiley:

**Comment by hiroko-lc101** [comment]
You're correct. I listed up the features for students more as future steps/nice-to-have additional features. I included them in my project outline to show another idea I have for Mathercise that I don't want to forget. I can either mark them as future additional features or remove them from the outline.

**Comment by r-spell** [comment]
Yeh I would have a "future additions" section, that sounds great!

**Comment by hiroko-lc101** [comment]
I've updated it with future additions section.

**Comment by hiroko-lc101** [comment]
Closing the issue
