### ISSUE TITLE
Project Outline- Technology

### ISSUE THREAD

**Issue by r-spell** [hiroko-lc101/liftoff-assignments#4]
Most of the technology you mention is used in LC101.  What are you going to incorporate which is new? It seems like with the charts maybe some JS? Or some api to help with charts? I would decide what you might use and list this in the technology section. 

If cutting down features means that you are not going to have a chart anymore, JS might still be something you could use to add to your app. JS can be helpful for whenever you want to click something and have the page view change without having to submit and reload the page, so it might be helpful in creating features that allow admins to mark answers as correct or incorrect.

**Comment by hiroko-lc101** [comment]
I was thinking Google Charts/JavaScript for various graphs, but if I cut down Progress monitoring feature with graphs, I need something else to use JavaScript - page redirecting perhaps?

**Comment by hiroko-lc101** [comment]
I'm now wondering if I could use JavaScript for input validation. For example, for Flash Card management when a user creates a flash card, I would like to check what's entered is a math addition or subtraction with the format 'some digits + "+"/"-" sign + some digits'.

**Comment by hiroko-lc101** [comment]
I think I can use a chart as a part of Fitness Test when it displays result.

**Comment by r-spell** [comment]
Both of these ideas sound great! I would start with basic features and then look into either JS validation or results Chart after you get the other basic parts running.
