### ISSUE TITLE
Project Outline - What I'll Have to Learn

### ISSUE THREAD

**Issue by r-spell** [hiroko-lc101/liftoff-assignments#5]
Not quite sure what you mean about "redirecting automatically." Can you explain more where that would come in and how that is different from redirects done in LC101?  

Also I would try and narrow down possible ways of making the chart. There's many mentioned in the stackoverflow link.

**Comment by hiroko-lc101** [comment]
Fitness Test contains a series of math questions (flash cards). Each question has a time limit to answer. Mathercise app needs to display one question then display the next one without the user clicking any button or link. It needs to automatically display questions one after another. I believe this is different from redirect done in LC101 and am not sure how to implement this.

**Comment by r-spell** [comment]
I think what you are talking about could be done with JavaScript.  Let's look at it when you are back, in person.  You could maybe start with a version where you just have 1 question for the fitness tests (silly I know!) for the time being to help structure things out.
